### ISSUE TITLE
Project & Task Closing / Timesheets

### ISSUE THREAD

**Issue by benwillig** [OCA/timesheet#121]
**Version: 11.0**

At the moment, during the timesheet encoding, user can select any project marked with "Allow timesheet = True". After selecting the project, user can select any task of the project.

The problem is that, depending on the task's stage, the task could have been closed or cancelled. So you might want to forbid user to encode timesheets for those tasks.

**Proposed design:**
- Add a "Allow timesheet" field on the task stage (project.task.type)
- Add a filter domain on the task (on the account.analytic.line task_id field) which only retrieves task linked to a stage which allow timesheet

**Comment by benwillig** [comment]
cc @sbidoul @phschmidt

**Comment by feketemihai** [comment]
@benwillig Can you put here the Odoo version, as far as i know, only on version 8.0 the module is available, 
https://github.com/OCA/hr-timesheet/tree/8.0/hr_timesheet_no_closed_project_task and you have a PR for v 10.0, https://github.com/OCA/hr-timesheet/pull/101.

**Comment by benwillig** [comment]
This issue is for v11. Indeed, there is a module in v10 which allow to mark a stage as 'closed' and an other one to prevent users to select a closed task. But the proposed design is more flexible. For example, you could forbid users to select a task which is in a "Draft" stage. This is something you can't do with the v10 module because a "draft" state might not be considered as "closed".

**Comment by sbidoul** [comment]
:+1: This concept of "allow timsheets" is a more precise semantics than a closed flag or state.

I'm wondering if we should put a hard constraint in addition to the filter domain on timesheet line.

**Comment by benwillig** [comment]
I didn't talk about it but yes, the constrains was implicit for me.
