### ISSUE TITLE
Any user can 'Approve' himself after submitting to the 'manager'

### ISSUE THREAD

**Issue by calundi** [OCA/timesheet#145]
Odoo11
I have tried all, even installing the timesheet and users complete new. But it's always the same.
After pressing the button "Submitting to the Manager' the Manager of course gets the ability to agree, but the user can do it same way directly afterwards with pressung the button 'Approve'.
But the user hat NO manager rights. 

By the way.....same happens on 'Try me on Runbot'....the DEMO user also get the 'approve' button, after sending the 'approve request to the manager'. If used, then the timesheet is done and the manager do not get any message for a timesheet approve for this user. (screenshots below)
![submit to manager screen](https://user-images.githubusercontent.com/7644302/49670990-afedb700-fa66-11e8-923f-c2aae2210f48.jpg)
![after submit to manager the demo user can approve himself](https://user-images.githubusercontent.com/7644302/49670997-b845f200-fa66-11e8-9492-a7e6cd5228c6.jpg)
![approved and ready -no messages anymore to the manager](https://user-images.githubusercontent.com/7644302/49671016-c85dd180-fa66-11e8-9e33-95925a91d3ef.jpg)

**Comment by calundi** [comment]
....forgotten to add my screen shots for a better docu of the issue

![benutzerrechte test](https://user-images.githubusercontent.com/7644302/49586451-8008bb80-f961-11e8-9e35-89ceb72378ce.jpg)

![wocheneintrag dem manager vorlegen](https://user-images.githubusercontent.com/7644302/49586469-8b5be700-f961-11e8-8847-fa78ebb54661.jpg)

![erwarte genehmigung](https://user-images.githubusercontent.com/7644302/49586483-94e54f00-f961-11e8-85b5-ed473b8d0580.jpg)

![eigenstandige genehmigung](https://user-images.githubusercontent.com/7644302/49586492-9b73c680-f961-11e8-8c38-957724c812e2.jpg)

**Comment by ghost** [comment]
@jbeficent maybe you have knowledge about this? i try it too and can confirm this ... issue?

**Comment by calundi** [comment]
indeed it's completely weird for me.... filling in an application (timesheets) for a manager and beside being able to approve itself, as if there wouldn't be no need waiting for the accepting of the manager.
Yesterday I got a hint from a user....to pick up a group for the approve button for only members of this group being allowed to get it on the screen. As a beginner of odoo, I'm still a kind of 'newbie'. I know how to pick up a group, but could not find a parameter to insert for the 'approve' button. The 'send for approve' is given, but I think that's the need for sending it to the manager.
Maybe I get some more infos of this user, who gave me the hint.
In addition there's the running timesheets_user group which perhaps need 1 or 2 parameters to get deleted.
I will try on and hope to get a solution....otherwise this addon I cannot use in a company where the employees can approve their weekly time sheets without a manager control.

**Comment by calundi** [comment]
Sadly no more informations or hints. Maybe it's no problem for many users, being able not to wait for the approve/validation of the manager, who only should do it.
So the last programming where it works well is Odoo 9. A bad luck to require working with a newer Odoo version.

**Comment by calundi** [comment]
Yesterday got a hint from India...but so short, that I don't know where/how to use it. Mentioned it, I'm a beginner of Odoo and for that kind I'm mainly working on the installation and app using inside.

Found the place where the mentioned code must be inserted.

< button name="action_timesheet_done" states="confirm" string="Approve" type="object" groups="hr_timesheet.group_timesheet_manager" class="oe_highlight"/ >

And now the timesheet works very very well as it should do....only the Manager is able to agree to the given timesheets of a user.

**Comment by alexey-pelykh** [comment]
In 11.0 and 12.0 (not sure about previous versions), the `hr_timesheet_sheet` module expects employee manager (set by `parent_id` of the `hr.employee` model) to approve the timesheets of their unit. Such manager does not have to be in `hr_timesheet.group_timesheet_manager` group for that. Correct fix is to limit the approver to be manager of employee who has submitted the timesheet

**Comment by alexey-pelykh** [comment]
References:
https://github.com/OCA/hr-timesheet/blob/51ecd66f7f6fd417fe7e22358c90cf5be54d564a/hr_timesheet_sheet/models/hr_timesheet_sheet.py#L367
should have extra check to ensure current user is `sheet.employee_id.parent_id.user_id.id`

also see https://github.com/OCA/hr-timesheet/blob/51ecd66f7f6fd417fe7e22358c90cf5be54d564a/hr_timesheet_sheet/models/hr_timesheet_sheet.py#L539
