### ISSUE TITLE
[12.0] hr_timesheet_sheet: error

### ISSUE THREAD

**Issue by alexey-pelykh** [OCA/timesheet#146]
![image](https://user-images.githubusercontent.com/345102/49581573-079efc00-f95b-11e8-9047-c7c1ba520bd7.png)

**Comment by alexey-pelykh** [comment]
Likely related to `web_widget_x2many_2d_matrix`

**Comment by alexey-pelykh** [comment]
https://github.com/OCA/web/pull/1124

**Comment by yajo** [comment]
This can be closed.
