### ISSUE TITLE
hr_timesheet_sheet: test_4 fails on specific day

### ISSUE THREAD

**Issue by alexey-pelykh** [OCA/timesheet#148]
It seems that when executed on Sunday, 19:00 GMT+2, it fails. It happens due to:
 * `timesheet_1` gets removed due to it's empty and name is `'/'`
 * `timesheet_3` does not get counted in since it's already next week so not counted in when test is performed on last day of the current week

Thus test has to be adjusted

**Comment by pedrobaeza** [comment]
Just cherry-pick my commit https://github.com/OCA/hr-timesheet/commit/4d1b0158945c178965389916a74f7ef0224e75bd#diff-f50417d68c94e59c4808fef50f941936 that I did tonight with the same problem in 11.0 :wink:

**Comment by alexey-pelykh** [comment]
Then I guess we can fast-merge that?

**Comment by pedrobaeza** [comment]
Yes, when CIs finish.
