### ISSUE TITLE
[11.0] hr_timesheet_sheet: creates trash entries in hr_timesheet_sheet_line table

### ISSUE THREAD

**Issue by lieblinger** [OCA/timesheet#185]
I've tried your module and it works great!

Expect one thing: I experienced that if I discard a timesheet, that there're still entries without sheet_id in the line table. It's also adding empty lines (hr.timesheet.line) on a page reload.

After I saved the timesheet there're still two entries for every day mapped to the according sheet in the table (+ the old unmapped entries).

Is this the normal behaviour?

**Comment by astirpe** [comment]
@lieblinger what you wrote sounds like a problem to me but I cannot reproduce the behavior you described. Am I missing something?
Could you add some information to help me to reproduce the problem?

**Comment by kumarinie** [comment]
@lieblinger I found the same issue with every time reload timesheet page, hr_timesheet_sheet_line entries are getting created with or without quantity.
Let me know if you already have any solution.
