### ISSUE TITLE
[11.0] hr_timesheet_sheet prevents invoice validation

### ISSUE THREAD

**Issue by j-zaballa** [OCA/timesheet#189]
https://github.com/OCA/hr-timesheet/blob/5e58e438a845fd706d75f14117ba4adea5062925/hr_timesheet_sheet/models/account_analytic_line.py#L60

The `_check_state` on method does not allow validation of invoices if the timesheet sheet is not in draft state. That seems fine. But on sale_timesheet addon's `_compute_timesheet_revenue` method of `account.invoice` model, the analytic lines's `timesheet_revenue` and `timesheet_invoice_id` fields are updated:

Here: https://github.com/odoo/odoo/blob/21e44d472dba0810bb7e8cc1d74d29ec3456ec95/addons/sale_timesheet/models/account_invoice.py#L113

And here: https://github.com/odoo/odoo/blob/21e44d472dba0810bb7e8cc1d74d29ec3456ec95/addons/sale_timesheet/models/account_invoice.py#L93

I can see that the `_check_state` method checks if there is a `skip_check_state` entry on context. But I can't find that it is been used to avoid the current behavior.

Now, I'm not a hundred percent sure about it, but I assume this is not the intended behavior. If I'm right and get some feedback, I'll try and fix it myself.

**Comment by pedrobaeza** [comment]
I think that `_check_state` shouldn't raise on all fields changes, but only on specific ones.

**Comment by j-zaballa** [comment]
A quick solution would be to override `_compute_timesheet_revenue` and call super with `skip_check_state` in context. I might be missing something though...

**Comment by pedrobaeza** [comment]
No, for me it's the other solution I said.

**Comment by jonerikceberio** [comment]
Yes, we talked exactly about that: making a list of fields that should be frozen when the timesheet is approved. Any modification to these fields should get a raise, anything else is green to go. I guess a method to determine this list of fields, so it is easily inherited

**Comment by pedrobaeza** [comment]
Yes, that's the way to go IMO.

**Comment by astirpe** [comment]
In https://github.com/OCA/hr-timesheet/pull/191 I'm proposing a fix for this issue. We use that fix in production.

**Comment by jonerikceberio** [comment]
Solved by #195
