### ISSUE TITLE
[11.0][BUG] hr_timesheet_sheet: Details tab not updated when changing Employee

### ISSUE THREAD

**Issue by astirpe** [OCA/timesheet#209]
Create a timesheet sheet:

```
Employee: Pieter Parker
Timesheet Period: from 03/18/2019 to 03/24/2019 (Week 12)

```
Add a line:

```
03/18/2019	Data Import/Export Plugin		Test1	01:00
```

Save. The data in the Summary tab is now aligned with Details tab.

Edit and change Employee: for example choose `Demo User`. Save.

Result:
Summary tab is empty (ok). Details tab is not updated and still displays the line (not ok).

Expected:
Details tab should be updated.

**Comment by MiquelRForgeFlow** [comment]
Why would you want to change the employee? If you want a different employee, then create a new timesheet sheet for that other employee.

**Comment by astirpe** [comment]
@mreficent that's exactly what the commit https://github.com/OCA/hr-timesheet/commit/455d28014be412dbcf8602e812484a085796ee4a does. But the super-powerful managers are also able to create timesheet sheets by setting an employee other than themselves.

**Comment by MiquelRForgeFlow** [comment]
Well, I mean, maybe we should forbid to change the employee when the sheet is already created, filled and saved.

**Comment by astirpe** [comment]
@mreficent that's exactly what the commit 455d280 does.

**Comment by MiquelRForgeFlow** [comment]
Oh, I see now :+1:
