### ISSUE TITLE
hr_timesheet_sheet: v11 vs v12

### ISSUE THREAD

**Issue by alexey-pelykh** [OCA/timesheet#235]
@mreficent @astirpe - shall we assemble a list of fixes/patches that need to be ported from v11 to v12 and backwards? As I don't feel confident that nothing will be lost/forgotten.

P.S. Should we have a Slack or other similar place to sync-up?

Summary:

 - ~**submit to manager in multicompany**: merged into v11 and v12~
 - ~**company on projects and employees**: merged into V11 and V12~
 - ~**fix constraint for company_id in lines**: merged into v11 and v12~
 - **texts & formatting / sheet name**: #183 in v12 (+ fix in #222), not backported to v11
 - ~**unlink only generated AAL**: #184 in v12 and v11 got it via #196~
 - **more extendability & cleanup**: #155 in v12, partially ported to v11 via #237
 - **various improvements**: ~#237 in v11 (previously #233)~, not ported to v12

**Comment by astirpe** [comment]
@alexey-pelykh from my side:

- **submit to manager in multicompany #224:** PR pending in V11, is already merged in V12
- **company on projects and employees #226 and #234:** PRs pending in V11 and in V12
- **fix constraint for company_id in lines #232:** PR pending in V12, is already merged in V11

I think you made some refactoring in V12 that was not backported to V11, right?

**Comment by alexey-pelykh** [comment]
From my side it was:

- **texts & formatting** / **sheet name**: https://github.com/OCA/hr-timesheet/pull/183 in v12 (+ fix in https://github.com/OCA/hr-timesheet/pull/222), not backported to v11
- **unlink only generated AAL**: https://github.com/OCA/hr-timesheet/pull/184 in v12 and v11 got it via https://github.com/OCA/hr-timesheet/pull/196
- **more extendability & cleanup**: https://github.com/OCA/hr-timesheet/pull/155 in v12, not backported to v11 (AFAIK)

**Comment by astirpe** [comment]
@alexey-pelykh will you take care of the backports?

**Comment by alexey-pelykh** [comment]
@astirpe sure, goal is to sync up and figure out next steps.

**Comment by alexey-pelykh** [comment]
Meanwhile #224 and #232 has been merged.

**Comment by alexey-pelykh** [comment]
Listed #237 in v11 (previously #233)

**Comment by pedrobaeza** [comment]
All merged, so I close.
