### ISSUE TITLE
HR Timesheet Sheet - update details lines

### ISSUE THREAD

**Issue by ACouasnonPerso** [OCA/timesheet#265]
Hello,

I present you my context: 
We have an Odoo V11 production base. 
We usually used version 8 to fill in the timesheets with hr_timesheet_sheet (from version 8 so) We recently switched to version 11 and the employees who had to fill in the timesheets raised a problem. 

It is required to save the timesheet on the module hr_timesheet_sheet to get the details of a timeline (correct day and duration). After checking, it is clearly indicated in the module description that this is the procedure to follow.
I was given the mission to modify this in order to be able to access the details without the need to save. 
**Would it be possible to help me by telling me why the need to save is present? And if you have any hints on how to do that, I'm a taker.** 

Thank you in advance for the time you will take to answer me.
Sincerely, 
Anatole

**Comment by pedrobaeza** [comment]
It's a technical limitation due to the framework. If you don't want that, then you'll need to work on doing things of JS side, which is very ugly. Better to instruct your users to get used to this. It's not enough annoying IMO for working in such hard changes.

**Comment by ACouasnonPerso** [comment]
Thank you for your answers and indications
