### ISSUE TITLE
[12.0] Analytic lines removed after timesheet removal

### ISSUE THREAD

**Issue by CasVissers-360ERP** [OCA/timesheet#267]
Hi, 

Why is this method run:
```
        analytic_timesheet_toremove = self.env['account.analytic.line']
        for sheet in self:
            analytic_timesheet_toremove += \
                sheet.timesheet_ids.filtered(lambda t: t.name == empty_name)
        analytic_timesheet_toremove.unlink()
```

If a user has created a timesheet/analytic line it should never be removed if the timesheet is removed?

**Comment by mrnull01** [comment]
> If a user has created a timesheet/analytic line it should never be removed if the timesheet is removed?

@CasVissers-360ERP Why is that?

**Comment by CasVissers-360ERP** [comment]
> > If a user has created a timesheet/analytic line it should never be removed if the timesheet is removed?
> 
> @CasVissers-360ERP Why is that?

First of all a line with the description '/' is not always empty or void. But most importantly the user indicates that the timesheet should be removed, not underlaying lines.
