### ISSUE TITLE
[10.0] hr_timesheet_sheet don't change amout on analytic line during modification existing record.

### ISSUE THREAD

**Issue by sluger25** [OCA/timesheet#271]
Hi,
I use the following modules:
_hr_timesheet_sheet
hr_timesheet_task
sale_timesheet_

I noticed a problem with the hr_timesheet_sheet module.
When you add a new record on the summary tab, the appropriate analytical entry with the correct value is created. But when you try to modify record on the _Summary tab_ (attached screenshot: ![srceen1](https://user-images.githubusercontent.com/44207615/63591120-1a6f6480-c5ae-11e9-9cf1-30a7379276fb.PNG) ), only the unit_amount changes in the analytical account and the amount remains.
When you make modifications on the _Details tab_, everything works fine and both unit_amout and amout change correctly.
Does anyone have a solution for this problem?

**Comment by pedrobaeza** [comment]
On v10, `hr_timesheet_sheet` is still part of Odoo core. Any way, v10 is end of life, so I doubt they would care about this issue, but you can try.
