### ISSUE TITLE
[RFC] maintenance_timesheet

### ISSUE THREAD

**Issue by dalonsod** [OCA/timesheet#274]
Hi all,

I'm currently working on a bridge module between `hr_timesheet` and `maintenance`. I'm not really sure about the most convenient repo destination for this addon (could also be `OCA/maintenance`). By now, it contains the following features:

- Adds project to equipments, with the ability of automatically creating it, or selecting and existing one.
- Adds project and task to a maintenance request. The project for a request is initially inherited from the equipment, with the ability of changing or unselecting it. A request created from cron will reflect the related inheritance.
- Adds timesheets to a request, the main goal of this addon. The timesheets will be automatically filled with the request project and task. Only request `user_id`, maintenance team users, and followers will be able to attach timesheets to the request. When creating and modifying timesheets, the request must have an undone stage.

What do you think about these features? Feel free to add your comments.

PS 1. When `maintenance/base_maintenance_group` addon is migrated to v12, it's possible to increase security in this `maintenance_timesheet` when accessing timesheets. 

PS 2. When this addon is finished, a `maintenance_plan_timesheet` addon is also planned

**Comment by dalonsod** [comment]
cc @jbeficent @ageficent @astirpe

**Comment by astirpe** [comment]
@dalonsod I think that would be a nice contribution!

Here my comments:

- about adding project to equipments and project and task to a maintenance request (point 1 and 2) it could be done in a separate module (eg.: `maintenance_project`) that would be not depending on timesheets;
- about timesheets to a request (point 3) module `maintenance_timesheet` would depend on `maintenance_project` and `hr_timesheet`;
- a future `maintenance_plan_timesheet` should be named `maintenance_timesheet_plan` instead;
- all the above modules seem to me better fitting in repo `maintenance`.

**Comment by dalonsod** [comment]
Thanks @astirpe !!
I'll follow your suggestions, starting with a first `maintenance_project` module in `maintenance` repo.

**Comment by dalonsod** [comment]
Well, addons `maintenance_project`, `maintenance_project_plan` and `maintenance_timesheet` ready for maintenance repo on v12.

Thanks for helping me @astirpe !!!!

Closing this thread.
