### ISSUE TITLE
[12.0][BUG] hr_timesheet_sheet_period: access rights

### ISSUE THREAD

**Issue by alexey-pelykh** [OCA/timesheet#288]
https://github.com/OCA/timesheet/blob/a6de0651bfc85260b4aac91fbcfb357ec35a595f/hr_timesheet_sheet_period/models/hr_timesheet_sheet.py#L80

shouldn't this be in `sudo`? Creator of sheet not always can access `hr.contract`

**Comment by alexey-pelykh** [comment]
@mreficent @aheficent ^

**Comment by AaronHForgeFlow** [comment]
I think you are right. In my use case, always the Timesheet manager is also Employee manager, but perhaps that is not always the case.

**Comment by alexey-pelykh** [comment]
Also, `test_end_date_before_start_date` seems to be affected by this module by default. Modules should not change behaviour out of the box :(

**Comment by AaronHForgeFlow** [comment]
Is that a method in standard odoo?

**Comment by alexey-pelykh** [comment]
That's test cast from `hr_timesheet_sheet`, I'm not 100% about conclusions, going to take a closer look soon

**Comment by alexey-pelykh** [comment]
Closing due to PR availability
