### ISSUE TITLE
Error on naming crm_phonecall_timesheet / crm_timesheet

### ISSUE THREAD

**Issue by legalsylvain** [OCA/timesheet#293]
![image](https://user-images.githubusercontent.com/3407482/69954422-8c374280-14fb-11ea-82d1-c7a1274fbb60.png)

The module crm_phonecall_timesheet and the module crm_timesheet have the same "display name" "CRM timersheet". I think that they should have distinct name.

regards.

CC : @Technativa, @pedrobaeza

**Comment by pedrobaeza** [comment]
Thanks for noticing. Fixed in 8cb5287
