### ISSUE TITLE
install the module in V12

### ISSUE THREAD

**Issue by SarahE3K** [OCA/timesheet#294]
module: hr_timesheet_sheet
version: 12.0

**Steps to reproduce**
- I installed the modules but when I go to setting to modify the date range and start day, I canno't edit it...

![image](https://user-images.githubusercontent.com/52499270/69984782-e0482400-1507-11ea-9a20-dd3b4fff8541.png)

 

How can I define a different sart day?

Many thanks for your help

**Comment by alexey-pelykh** [comment]
It's not reproducible on Odoo CE, @pedrobaeza sorry for bothering, any ideas where to look at for origin?

**Comment by pedrobaeza** [comment]
Unless there are clear steps to reproduce the problem in CE, we can't do more, so closing.
