### ISSUE TITLE
[RFC] hr_timesheet_sheet_reminder

### ISSUE THREAD

**Issue by alexey-pelykh** [OCA/timesheet#298]
@pedrobaeza @mreficent @astirpe I want to add a module that would make message reminder to submit a finished period, and wanted to gather your input if such exists on name and features. So far seems that "send reminder if there was something to submit during the period" sounds reasonable enough + option to remind "before/after" days, e.g. 2 days before will send a reminder at noon 2 days before the end of period

**Comment by pedrobaeza** [comment]
I don't like that approach of hammering with reminders everywhere. It's better to set an activity (maybe automatically like in `hr_holidays` module) for this, and this can be in the core module.

**Comment by alexey-pelykh** [comment]
Please elaborate, I have no idea what activity is and how it can help :D

**Comment by pedrobaeza** [comment]
Activities is something in Odoo standard since 11.0. https://www.odoo.com/documentation/user/12.0/discuss/plan_activities.html

**Comment by alexey-pelykh** [comment]
@MiquelRForgeFlow @astirpe would you like to see this as separate module? Or in base?

**Comment by astirpe** [comment]
Separate module please. And as Pedro said, activities can do the job.

**Comment by alexey-pelykh** [comment]
@astirpe yep, I've researched how `hr_holidays` does that, and it seems that openchatter is already supported in `hr_timesheet_sheet` as well as `mail.activity.mixin` is also used already, thus I don't really think this feature should be in a separate module, but I remember your vision that module is overloaded.

**Comment by alexey-pelykh** [comment]
@astirpe I've evaluated how much code it will be - yeah, it will be a separate module, `hr_timesheet_sheet_activity` 👍

**Comment by alexey-pelykh** [comment]
Submitted a #317 PR
