### ISSUE TITLE
Fix PEP8 on 7.0 branch

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/timesheet#3]
I open this issue to avoid duplicating efforts. I'm doing this work.

**Comment by eLBati** [comment]
See https://github.com/eLBati/hr-timesheet/tree/7.0_fix_pep8 if you need.
I stop for now

**Comment by pedrobaeza** [comment]
Sorry for not publishing before...

**Comment by eLBati** [comment]
The same goes for me :worried:
Did we duplicate much work yet?
I fixed all the modules except `hr_attendance_analysis` and `timesheet_task`

About `hr_attendance_analysis`, @tafaRU is preparing several changes for several bugs (https://code.launchpad.net/~agilebg/hr-timesheet/fix-hr_attendance_analysis-various-bugs).
Maybe the PEP8 changes would conflict with them, I'm not sure

**Comment by pedrobaeza** [comment]
Well, that it's the module I left, but don't worry, for the next time we will talk before. Better if @tafaRu waits for the refactoring.

Regards.

**Comment by dreispt** [comment]
Maybe to avoid overlapping work Issues could be used to "announce" work in progress. Just an idea...

**Comment by pedrobaeza** [comment]
Yeah, it can be, like I did in this one :)

**Comment by eLBati** [comment]
For reference: https://github.com/OCA/hr-timesheet/pull/6

**Comment by bwrsandman** [comment]
Fixed with #6
