### ISSUE TITLE
timesheet uom float in projects

### ISSUE THREAD

**Issue by miscs** [OCA/timesheet#332]
Hi all,

in projects the logged time is shown as float, which transforms for example 4:30 hours to 4.5.
Is this an error in the view or a configuration I am too blind to find?

Thanks!
Stephan

<img width="596" alt="timesheet_uom" src="https://user-images.githubusercontent.com/878463/74875382-71d66d80-5362-11ea-864c-1fef31341767.png">

**Comment by alexey-pelykh** [comment]
That's expected result since 4 hours 30 minutes is 4 and half (4.5 decimal) hours

**Comment by alexey-pelykh** [comment]
cc @pedrobaeza that's your module? :P

**Comment by pedrobaeza** [comment]
The problem is a migration with OpenUpgrade and some UoMs not updated in the field that says which widget to use. Am I guessing correctly?

**Comment by miscs** [comment]
Thanks for the fast answers!
@pedrobaeza Your guess is correct. So to fix it I need to edit the views and add the correct UoMs to the fields I suppose?

**Comment by pedrobaeza** [comment]
No, it's a hidden field at UoM level.

**Comment by miscs** [comment]
OK, thanks for the pointers!
