### ISSUE TITLE
Write Access Problem caused by hr_timesheet_sheet_attendance

### ISSUE THREAD

**Issue by wpichler** [OCA/timesheet#382]
Hi all,

we do have a write access denied problem in a multi company odoo 12 environment with the hr_timesheet_sheet_attendance module installed. As soon as an employee wants to create a new timesheet he does get the write denied error.

This get caused by this part of code:
https://github.com/OCA/timesheet/blob/4754d2b1e6bedeb0641b3fcd4f9982064c3a983d/hr_timesheet_sheet_attendance/models/hr_timesheet_sheet.py#L86

In this part attendance records without timesheet will get searched - and timesheets should get attached if one exists.
But it does search for all attendance records - and does not query for the employee's records. So the error can happen...

I've added "('employee_id', '=', vals['employee_id'])," to the domain to get it working

**Comment by pedrobaeza** [comment]
Can you propose the PR?

**Comment by wpichler** [comment]
https://github.com/OCA/timesheet/pull/383
