### ISSUE TITLE
[13.0] User permissions for hr_timesheet

### ISSUE THREAD

**Issue by dl-lim** [OCA/timesheet#388]
Hey, new to the odoo ecosystem. Using odoo 13 now - Thus also downloaded the 13.0 branch of OCA/timesheet

I'm not sure if I'm missing anything, but the original hr_timesheet module does not have a user group that only allows an employee to view and modify their own timesheets only. I am left with these options when creating a new user:
![image](https://user-images.githubusercontent.com/69715968/93927652-c3593780-fd4b-11ea-93c4-02c369fabaca.png)
 
Leaving it blank disables the whole timesheet app on the user side. Setting it to the lowest level (See all timesheets), allows the user to view timesheets submitted by other users. Surely there's a way to prevent this? Isn't this supposed to be available out-of-the-box?

Also looking forward to testing the hr_timesheet_sheet module, as I suppose this is more suited for a weekly upload type of submission, yes?

**Comment by pedrobaeza** [comment]
Which module is that? I don't think it's from this repository.

**Comment by dl-lim** [comment]
yes, it isn't in this repository, could you point me to the right place to post this? OCA/timesheet modules seem to depend on this

**Comment by pedrobaeza** [comment]
Questions must be done on forums, not on GitHub issues, that are for problems/bugs in the corresponding repository. Closing this then.

**Comment by dl-lim** [comment]
Common bug, it seems
https://www.odoo.com/forum/help-1/question/odoo-13-timesheet-minimum-user-permission-is-see-all-timesheets-171342
