### ISSUE TITLE
[12.0] sale_timesheet_limit_date: Tests red due to upstream change

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/timesheet#391]
@guewen @simahawk it seems this module is failing now in main branch due to a change upstream:

https://travis-ci.org/github/OCA/timesheet/builds/730268987

can you please check?

**Comment by pedrobaeza** [comment]
It seems due to https://github.com/odoo/odoo/commit/4f06157fb7120de3317f4ac7de5c97757e8a542c

**Comment by pedrobaeza** [comment]
Any news?

**Comment by simahawk** [comment]
checking

**Comment by pedrobaeza** [comment]
Thanks!
