### ISSUE TITLE
Issue from en_AU translation in po file for weeks %s, seems to affect many translations

### ISSUE THREAD

**Issue by gdgellatly** [OCA/timesheet#407]
https://github.com/OCA/timesheet/blob/06d1a741b1ea293dbcea34f101f643b12c654459/hr_timesheet_sheet/models/hr_timesheet_sheet.py#L207

Sorry, no time to fix right now. Basically the comma on this line causes an issue with number of arguments in string formatting.

EDIT: Above is wrong.
Error comes from this commit
https://github.com/OCA/timesheet/commit/ba33f6437662e8f7e08102c15cbb5d54ef46b26e

**Comment by alexey-pelykh** [comment]
It should not cause it, since there's 1 element in tuple and 1 formatting argument, please see https://repl.it/@AlexeyPelykh/FuchsiaSnowCopyright#main.py. Please check the localization you're using.

**Comment by gdgellatly** [comment]
@alexey-pelykh I can assure you that line does cause the issue. I can simply change the date to one more than a week out and it works fine

**Comment by alexey-pelykh** [comment]
What localization are you using? Is it reproducible on runbot?

**Comment by alexey-pelykh** [comment]
And in any case removing coma _is not a fix_

**Comment by gdgellatly** [comment]
OK, but you closed the issue, not the fix. The localization is en_US or en_AU. Neither of those have this term translated as it is identical in whatever version of English you speak.

**Comment by alexey-pelykh** [comment]
What's the error message? Is it reproducible on runbot?

**Comment by gdgellatly** [comment]
@alexey-pelykh I don't know about runbot, but here is a simple shell session output, python v3.6.12

```
>>> period_end = sheet.date_end.strftime(
...                 '%V, %Y'
...             )
>>> period_end
'49, 2020'
>>> from odoo import _
>>> name = _('Week %s') % (
...                     period_end,
...                 )
Traceback (most recent call last):
  File "<console>", line 2, in <module>
TypeError: not all arguments converted during string formatting
>>> name = _('Week %s') % period_end
Traceback (most recent call last):
  File "<console>", line 1, in <module>
TypeError: not all arguments converted during string formatting
>>> period_end
'49, 2020'
>>> name = _('Week {}').format(period_end)
>>> name
'Week 49, 2020'
>>>

**Comment by alexey-pelykh** [comment]
@gdgellatly if it's not reproducible on runbot, it's something about your instance. What's the output of `_('Week %s')`?

**Comment by alexey-pelykh** [comment]
Since `_('Week {}')` and `_('Week %s')` is absolutely different thing

**Comment by gdgellatly** [comment]
@alexey-pelykh Sorry I was looking at wrong version. You are correct. Culprit is the v13 en_AU translation. I just delete the terms and it works fine now. 

Compare https://github.com/OCA/timesheet/blob/06d1a741b1ea293dbcea34f101f643b12c654459/hr_timesheet_sheet/i18n/en_AU.po#L987 and https://github.com/OCA/timesheet/blob/4858845e3469c37bbf5c81e9ea8d63e326370bd9/hr_timesheet_sheet/i18n/en_AU.po#L964

**Comment by alexey-pelykh** [comment]
Yeah, `#, fuzzy, python-format` strikes again. @sbidoul @pedrobaeza let's finally do something about that

**Comment by sbidoul** [comment]
I did disable fuzzy merges on all weblate components a while ago. I'll check again. weblate is behaving strangely wrt default values for bools I think.

**Comment by alexey-pelykh** [comment]
@sbidoul oh, awesome! double thanks!
