### ISSUE TITLE
Analysis does not take into account employee creation date / activation date

### ISSUE THREAD

**Issue by glm-vgoineau** [OCA/timesheet#445]
In hr_utilization_analysis 

For example, if employee is activated/created in march and I create report from January to march... capacity include new employee for every period of time.

**Comment by alexey-pelykh** [comment]
Hi @glm-vgoineau, yes, that's a design limitation that it does not take into account employee's contract start/end dates, because underlying Odoo computations do not take that into account. That can be improved, yet not deemed as an issue.

**Comment by glm-vgoineau** [comment]
Thanks for reply. Could we suggest pr for that. Our team will "improve it"

Regards

[GLM Conseil]<https://www.glmconseil.com>        Vincent Goineau
 ASSOCIÉ

 221 Rue Saint-Jean
 Longueuil, QC J4H 2X4
 Tel.: 514 GESTION ext 102
 ***@***.***



________________________________
De : Alexey Pelykh ***@***.***>
Envoyé : 16 avril 2021 07:59
À : OCA/timesheet ***@***.***>
Cc : Vincent Goineau ***@***.***>; Mention ***@***.***>
Objet : Re: [OCA/timesheet] Analysis does not take into account employee creation date / activation date (#445)


Hi @glm-vgoineau<https://github.com/glm-vgoineau>, yes, that's a design limitation that it does not take into account employee's contract start/end dates, because underlying Odoo computations do not take that into account. That can be improved, yet not deemed as an issue.

**Comment by alexey-pelykh** [comment]
PRs are welcome :)
