### ISSUE TITLE
[14.0] Do not merge invoiced timesheet lines

### ISSUE THREAD

**Issue by CasVissers-360ERP** [OCA/timesheet#463]
**Description** 
Method def clean_timesheets(self, timesheets) removes invoiced timesheet lines which **can** result in an error since invoiced timesheet lines can't be removed (sale_timesheet base)

**Steps to reproduce**
Create multiple timesheet lines on the same project with description '/' and invoice them, remove the timesheet back to draft, when writing on the timesheet:
raise UserError(_('You cannot remove a timesheet that has already been invoiced.'))

**Suggestion to fix**
repeated = timesheets.filtered(lambda t: t.name == empty_name and not t.timesheet_invoice_id) I think the lines should be ignored.

**Comment by bosd** [comment]
Thanks for this. I was experiencing odd problems in production. Couldn't pinpoint it. :smiley:
