### ISSUE TITLE
[Odoo14] Timesheet  - ValueError: Invalid field 'device_id' on model 'hr.employee.public' when not in HR Group

### ISSUE THREAD

**Issue by aduijs** [OCA/timesheet#479]
My employees have been getting the following error when trying to creat a timesheet.
ValueError: Invalid field 'device_id' on model 'hr.employee.public'

this only appears when they are not members of the "human resource - employee"  group as an officer or admin. (those two groups have no issues)
just the groups with left blank and kiosk attendance get this error (file attached)
[error.txt](https://github.com/OCA/timesheet/files/8316642/error.txt)

**Comment by pedrobaeza** [comment]
And why do you think it's related to something in this repo? The mentioned field is not from here.

**Comment by aduijs** [comment]
because it is from timesheet sheet

**Comment by aduijs** [comment]
as officer admin it works normal
![image](https://user-images.githubusercontent.com/7501203/159294138-4ee1c8c6-cf2f-464d-9eaa-87e789baf9fa.png)
but as normal employee it throws
![image](https://user-images.githubusercontent.com/7501203/159294276-9dd3526d-366f-41bf-8738-31073efd4731.png)

**Comment by aduijs** [comment]
found the issue: hr_zk_attendance by Cybrosys is causing the problem.
removing the biometric device integration solved the issue
