### ISSUE TITLE
[8.0] Add partner_id in account.analytic.line

### ISSUE THREAD

**Issue by rafaelbn** [OCA/timesheet#49]
Hello,

I would like to know opinnion / discuss solutions with resposibles of this project.

As you know Odoo v9 adds partner_id in account.analytic.line.

I'm talking with @pedrobaeza to make a module which add this information also in v8

Have any of you thought about this? For me is very common to have a only one account.analytic.account for many customers.

Thanks
Regards
Rafael

(cc @eLBati @yvaucher @guewen  @dreispt )

**Comment by yvaucher** [comment]
It seems reasonable to have a separate module that adds only the partner_id on account.analytic.line on which other modules could depend.

So I guess it would also need adaptation on timesheet to be able to specify for which customer you worked on your timesheet line. And certainly in other places.

Do you plan to backported this from v9 ?

**Comment by rafaelbn** [comment]
Closing, we did:
- https://github.com/OCA/account-analytic/tree/8.0/analytic_partner
- https://github.com/OCA/account-analytic/tree/8.0/analytic_partner_hr_timesheet
