### ISSUE TITLE
[8.0] hr_timesheet_task - Improve ussability (don't show task done or canceled)

### ISSUE THREAD

**Issue by rafaelbn** [OCA/timesheet#51]
If you are in "Timesheet activities" when you create a new one you must field:
- Date
- User
- Description
- Analytic Account
- Task (optional) <-- Here is where we must improve

After selecting "Analytic Account" in Task it shows you all task of the project related, but it musn't show task done or cancelled to be faster.

**Comment by yvaucher** [comment]
Edited title, task_id is defined in `hr_timesheet_task` module not in `timesheet_task`

**Comment by sbidoul** [comment]
One problem we have to hide closed tasks is that the "closed" flag on task is in the wrong module in odoo. To get it we'd need to depend on sale_service which in turn pulls a lot of dependencies.

@adrienpeiffer made https://github.com/odoo/odoo/pull/8186 to change this.

**Comment by rafaelbn** [comment]
Hi, we must do this in OCA as Odoo answer:

```
Hello Rafael,

As stated in our contributing policy, we only accept proposals solving blocking issues in stable releases.

Improvements are not accepted in stable releases, such as 8.0.

For more information, please read:
https://github.com/odoo/odoo/wiki/Contributing#what-does-stable-mean
```

**Comment by sbidoul** [comment]
@rafaelbn we have this module https://github.com/acsone/acsone-addons/tree/8.0/hr_timesheet_no_closed_project_task that does what you want. We can move it to OCA.

It currently depends on https://github.com/odoo/odoo/pull/8186 but we'd be happy to redeclare the `closed` field on project.task.stage in a separate module, to avoid that dependency on the PR that will not be merged.

**Comment by sbidoul** [comment]
@rafaelbn I submitted https://github.com/OCA/project/pull/142 to have the closed flag available without sale_service. Can you review it?

When that is merged we'll propose https://github.com/acsone/acsone-addons/tree/8.0/hr_timesheet_no_closed_project_task to OCA.

**Comment by rafaelbn** [comment]
Hi @sbidoul , I think https://github.com/OCA/project/pull/142 should go OCB. We will review it of course.

Thanks a lot

**Comment by sbidoul** [comment]
@rafaelbn see https://github.com/OCA/hr-timesheet/pull/70

**Comment by rafaelbn** [comment]
Closing because https://github.com/OCA/hr-timesheet/pull/70
