### ISSUE TITLE
[8.0] hr_timesheet_improvement - What's mean DESC order

### ISSUE THREAD

**Issue by rafaelbn** [OCA/timesheet#52]
module: hr_timesheet_improvement
version: 8.0

**Steps to reproduce**
- Go To Human Resources - > Time Tracking - > Timesheet activities
- Check how are ordered Timesheet activities (hr.analytic.timesheet)

**Current behavior**
- You can check they have DESC order by date (without time)
- If you have 100 hundred per day, lines are ordered DESC order by?

**Expected behavior**

As described in README.rst

> Modifies timesheet behavior:
> Ensure a DESC order on timesheet lines

DESC order by name / by date / by Analytic Account?

**Comment by rafaelbn** [comment]
@yvaucher @vrenaville @charbeljc @damdam-s you are contributors of this module and I guess you are using them un customers. Could you clarify me this? Thanks a lot!

**Comment by damdam-s** [comment]
@rafaelbn https://github.com/OCA/hr-timesheet/blob/8.0/hr_timesheet_improvement/hr_timesheet.py#L30
order by analytic_line date and then by analytic account name

**Comment by rafaelbn** [comment]
OK, thanks.
