### ISSUE TITLE
[14.0][hr_timesheet_sheet] Timesheet shows less reported hours when user no longer has the rights to access the project

### ISSUE THREAD

**Issue by JordiBForgeFlow** [OCA/timesheet#521]
## Module
hr_timesheet_sheet

## Describe the bug
Timesheet shows less reported hours when user no longer has the rights to access the project

## To Reproduce
**Affected versions**: 14.0 (perhaps others)

1. Create a project, and assign visibility to all internal users
2. Report hours on this project
3. Change the visibility of the project, and assign to another user
4. Access to the timesheet sheet. The hours reported have disappeared.

**Expected behavior**
The hours reported should always be visible in the timesheet sheet. Even reporting new hours should be possible. But should not be possible to add the project to any new timesheet sheet.

cc  @MiquelRForgeFlow

**Comment by MiquelRForgeFlow** [comment]
Solved in https://github.com/OCA/OpenUpgrade/pull/3575.
