### ISSUE TITLE
[15.0] pre-commit: pylint with optional checks failed

### ISSUE THREAD

**Issue by CRogos** [OCA/timesheet#539]
## Module
pre-commit 
## Describe the bug
On several PR the pre-commit job fails. 

```
pylint with optional checks..............................................Failed
- hook id: pylint
- duration: 0.05s
- exit code: 1
Traceback (most recent call last):
  File "/home/runner/.cache/pre-commit/repouv58kqov/py_env-python3/bin/pylint", line 8, in <module>
    sys.exit(run_pylint())
             ^^^^^^^^^^^^
```

https://github.com/OCA/timesheet/actions/runs/3385867202/jobs/5624532199
https://github.com/OCA/timesheet/actions/runs/3386641459/jobs/5626308278
## To Reproduce
**Affected versions**:
14.0, 15.0

**Comment by yostashiro** [comment]
Same error here. https://github.com/OCA/commission/actions/runs/3392888681/jobs/5639598266

**Comment by pedrobaeza** [comment]
You have to update the copier template.
