### ISSUE TITLE
[8.0] ¿Same description means same functionality? timesheet_task = hr_timesheet_task

### ISSUE THREAD

**Issue by rafaelbn** [OCA/timesheet#54]
This two modules say exactly the same in description. Do they have the same functionality?

They have diferent functionality so the must have diferent description, and diferect usage section.

https://github.com/OCA/hr-timesheet/tree/8.0/timesheet_task

>  'description': """
> Replace task work items (project.task.work) linked to task with
> timesheet lines (hr.analytic.timesheet).

timesheet_tast: **_Analytic Timesheet In Task**_

https://github.com/OCA/hr-timesheet/tree/8.0/hr_timesheet_task

> 'description': """Replace project.task.work items linked to task
>                   with hr.analytic.timesheet""",

hr_timesheet_tast: **_Task in time sheet**_

Please @anthony-muschang @charbeljc review and change README.rst.  Thanks a lot.

**Comment by rafaelbn** [comment]
Hi @nbessi could you review this issue please?

**Comment by nbessi** [comment]
@rafaelbn `hr_timesheet_task` depends on `timesheet_task` and `hr_timesheet_sheet`. 
It alter the timesheet sheet view to add inside timesheet sheet all requiered fields and behaviors. We should fix the description as the one module alter root task management and the second alter timesheet management.

**Comment by rafaelbn** [comment]
Hi @nbessi as you said `We should fix the description as the one module alter root task management and the second alter timesheet management`. I'm closing issue. It could be great if you could change readme. cc @elicoidal
