### ISSUE TITLE
Filtering the timesheet line treeview by "product" doesn't work

### ISSUE THREAD

**Issue by mktsrl** [OCA/timesheet#558]
## Module
account.analytic.line 

## Describe the bug
I manage projects that are created automatically when certain services are sold.
The tasks of these projects make use of time sheets.
From the global list of all timesheets (accessible from the related app), the custom filter that allows you to search for them by "product" does not work and always shows an empty list

## To Reproduce
**14.0**:

1. need to install this module: Project anche HR Timesheet Sheet
2. Configure a new product of type "service". Further configure the service so that on "sale" it creates a new project linked to the "hour sheet": Billing policy = Timesheets on jobs, Service Tracking = Create a new project with no jobs
3. Now create a new sales order using the product you just configured
4. Upon order confirmation, a new project will be created: insert some timesheets
5. From the "Timesheets" app, now access the "All timesheets" menu
6. Filter the list using the "Product" custom filter and entering the name of the service created in step 2
7. the list will be empty

![image](https://user-images.githubusercontent.com/85298941/214081682-6cb8b959-576e-4506-a711-70b87c5dddcd.png)

**Expected behavior**
I would like to be able to filter the timesheet tree view for the linked product: timesheet > (project) task > sale oreder line > product template name

**Additional context**
Ubuntu 20.4 - Python 3.8

**Comment by pedrobaeza** [comment]
This is not how such column works (it's only filled on invoice lines generating analytic entries), and this is not something for this repository, as has nothing to do with any of the modules hosted in it.
