### ISSUE TITLE
Field "Other partner" empty when registering hours from Registered Calls

### ISSUE THREAD

**Issue by janetrp** [OCA/timesheet#62]
module: crm_timesheet
version: 8.0

**Steps to reproduce**
1- enter in the customer form
2- click on calls
3- fill the call content
4- let the clock run fo r a while
5- stop the clock

**Current behavior**
in HR/Timesheet activities/ Other partner field remains empty
![2015-10-05 17_08_05-devel - customers - odoo](https://cloud.githubusercontent.com/assets/13853118/10284393/1f4c1d32-6b84-11e5-97a7-54f93cb81d36.png)
![2015-10-05 17_08_31-devel - logged calls - odoo](https://cloud.githubusercontent.com/assets/13853118/10284403/25c4b5b6-6b84-11e5-964d-f88a78a89fe5.png)
![2015-10-05 17_09_49-devel - timesheet activities - odoo](https://cloud.githubusercontent.com/assets/13853118/10284410/2bbe5576-6b84-11e5-9b06-350a9e6b8c33.png)

**Expected behavior**

Partner name in Other Partner field and contact
![2015-10-05 17_12_01-devel - timesheet activities - odoo](https://cloud.githubusercontent.com/assets/13853118/10284518/ac206114-6b84-11e5-9b81-861c4ef477e6.png)

**Comment by pedrobaeza** [comment]
That's because there's no crm_timesheet_analytic_partner glue module that bridges both.

**Comment by janetrp** [comment]
@pedrobaeza is it possible to create the bridge?

**Comment by pedrobaeza** [comment]
@JavierIniesta, maybe you can do this glue module
