### ISSUE TITLE
Attached files does not appear in Surveys Sendings

### ISSUE THREAD

**Issue by janetrp** [OCA/timesheet#65]
I've prepared a survey.
When trying to send it I've attached a jpeg and sent it.

![2015-10-30 14_27_14-surveys - odoo](https://cloud.githubusercontent.com/assets/13853118/10846786/73b5b152-7f12-11e5-9920-6327e5ec92ab.png)

I have received ok the survey but not the attachments.
![2015-10-30 14_26_00-clipboard](https://cloud.githubusercontent.com/assets/13853118/10846760/46dab2cc-7f12-11e5-9733-fed94aa5652b.png)

**Comment by rafaelbn** [comment]
@janetrp you have open this PR in https://github.com/OCA/hr-timesheet/ and you must open here https://github.com/odoo/odoo/issues 
Please cc me
