### ISSUE TITLE
reporting: statistics on timesheets

### ISSUE THREAD

**Issue by lraffler** [OCA/timesheet#67]
the sum is not correct. 
some attendance time is not added if there are different entries on a day,
even if the constraints are fullfilled!

**Comment by sbidoul** [comment]
Can you provide more information on the issue you are encountering:
- which module have you installed?
- which report are you trying?
- actual result and expected result?

**Comment by lraffler** [comment]
Installed regarding to "Attendance"
hr_attendance
hr_timesheet_sheet
hr_timesheet_invoice

Reporting > Attendance Analysis group by day
doesn't sum up correct. It's unclear which attendance is included and why others are excluded?
