### ISSUE TITLE
Timesheets: calculate hours based on their invoiceability

### ISSUE THREAD

**Issue by lraffler** [OCA/timesheet#68]
We use timesheets with tasks and add time and define the invoiceability (0-100%)
The task statistics should show the invoicable hours and not the total number of hours (or both).
On project level the same: especially if there are "prepaid service units", only the accountable hours should be taken into account for calculating the "remaining units".

The calculations now are wrong and don't fullfil minimal requirements for a good timesheet management.

**Comment by pedrobaeza** [comment]
This is not something related with this repository, as this expands core's possibilities. You have 2 choices:
- Report this issue to Odoo itself.
- Make a module that fills this gap and propose here.
